# Spring Application Name
spring.application.name=backend
server.port=8081

# Database Configuration (Neon Cloud DB)
spring.datasource.url=jdbc:postgresql://ep-rough-haze-atqmslkp-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_f59NnhjalGQH

# JWT signing secret (HMAC-SHA256, 32+ bytes)
jwt.secret=616a5e179a7c0671fa128baf4756aa9a63ee26a00bda6ae704c96472491b0f9c

# JPA / Hibernate Configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# File Upload Limits
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB