# Spring Application Name
spring.application.name=backend
server.port=8081

# Database Configuration (Neon Cloud DB)
spring.datasource.url=jdbc:postgresql://ep-rough-haze-atqmslkp-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_f59NnhjalGQH

# JPA / Hibernate Configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect